# Generated by Django 3.2.3 on 2021-05-13 22:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('webhook_url', models.URLField()),
                ('api_key', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('content_length', models.IntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('request_headers', models.JSONField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=50, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_reference', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('successful', 'completed transaction'), ('pending', 'pending transaction'), ('failed', 'failed transaction')], default='successful', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='microservice.clients')),
            ],
        ),
    ]
