# Generated by Django 3.2.2 on 2021-05-12 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microservice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='client_id',
            new_name='client',
        ),
    ]
