# Generated by Django 3.2.2 on 2021-05-13 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microservice', '0006_alter_requestlogs_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestlogs',
            old_name='request_meta',
            new_name='request_headers',
        ),
    ]
