# Generated by Django 3.2.2 on 2021-05-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservice', '0007_rename_request_meta_requestlogs_request_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('successful', 'completed transaction'), ('pending', 'pending transaction'), ('failed', 'failed transaction')], default='successful', max_length=10),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_reference',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
