# Generated by Django 3.2.2 on 2021-05-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservice', '0008_auto_20210513_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestlogs',
            old_name='body',
            new_name='request_body',
        ),
        migrations.AddField(
            model_name='requestlogs',
            name='response_body',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
